CREATE DATABASE IF NOT EXISTS spookydb;
USE spookydb;

DROP TABLE IF EXISTS TopUsuario;
DROP TABLE IF EXISTS Usuario;

CREATE TABLE Usuario(
	usuarioID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    usuarioUser VARCHAR(30) UNIQUE NOT NULL,
    usuarioPass VARCHAR(30) NOT NULL,
    usuarioHighscore MEDIUMINT
);

CREATE TABLE TopUsuario(
	topID INT AUTO_INCREMENT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuarioID INT NOT NULL,
	FOREIGN KEY(usuarioID) REFERENCES Usuario(usuarioID)
);